#!/usr/bin/env python
# encoding: utf-8

# Python 2/3 compatibility
from __future__ import division, absolute_import, print_function, unicode_literals

import itertools
import sys
import time

from notify import notify

def main():
    icons = itertools.cycle(["kde", "konqueror", "document-open", "kmail"])
    lines = itertools.cycle(range(1, 5))

    appname = sys.argv[0]
    id = notify(appname, "ReplaceId test", "Body before replacement")
    while True:
        time.sleep(0.5)
        idx = lines.next()
        title = "ReplaceId test {}".format(idx)
        body = "Brand new body\n" * idx
        notify(appname, title, body.strip(), replaces_id=id, icon=icons.next())

    return 0

if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
